### ISSUE TITLE
Crash 'n Burn keeps rebooting

### ISSUE THREAD

**Issue by bigboo3000** [libretro/4do-libretro#18]
Hi
Crash 'n Burn keeps rebooting and it's impossible to go to start menu and to play.

It seems the bug is somewhat fixed in latest 4do version 1.3.2.4,
http://wiki.fourdo.com/Compatibility_List#Crash_.27n_Burn

Can you backport fixs from this latest version to make this game works?

Thanks

**Comment by hizzlekizzle** [comment]
Yeah, fixes can probably be backported but we need to know what actually did it. If you can find a commit that fixed it, we can try to reproduce it.

**Comment by bigboo3000** [comment]
I see but i'm not enough skilled to understand code and find the right commit.

it seems libretro core is based on 1.3.2.3, latest 4do is 1.3.2.4, it is not possible to merge all core changes between them in /trunk/FreeDOCore/FreeDO ?

https://sourceforge.net/p/fourdo/code/389/?page=2

**Comment by Tasosgemah** [comment]
Any news about this issue?

The core seems to have been updated about 10 days ago but the issue still remains

**Comment by Mortico** [comment]
Please fix this, I'm no developer or I'd do it myself.

**Comment by Tasosgemah** [comment]
Issue still exists after the last update on the buildbot.

**Comment by yahreen** [comment]
+1

**Comment by hizzlekizzle** [comment]
If someone could pinpoint when it got fixed upstream using these archived releases, that would help us narrow down the commit range we need to look at:
https://sourceforge.net/projects/fourdo/files/

**Comment by rcaridade145** [comment]
If you look at https://sourceforge.net/p/fourdo/code/389/tree//trunk/FourDO/Emulation/GameConsole.cs?diff=5144d6625fcbc97910ff4855:388 it adds a new case for crash and burn

**Comment by rcaridade145** [comment]
https://github.com/libretro/4do-libretro/blob/master/libfreedo/_3do_sys.c#L329 Fix mode seems to be commented on this branch so those fixes and others are not applied.

**Comment by rcaridade145** [comment]
@hizzlekizzle i narrowed down to that section but maybe someone like @twinaphex can if this is meant to be commented for now port wise?

**Comment by trapexit** [comment]
I'm planning to look into this.

**Comment by rcaridade145** [comment]
The problem is as far as i can tell that https://sourceforge.net/p/fourdo/code/389/tree/trunk/FourDO/Emulation/GameConsole.cs#l417 is not implemented in libretro so you can't get the record.Id and apply the corresponding fix.
Games affected are  Crash 'n Burn (JP) ,Crash 'n Burn (US),Street Figthter 2, Microcosm ,Alone in the Dark and  Samurai Shodown (EU-US-JP)

**Comment by trapexit** [comment]
I suspect it was left out because you'd need to replicate the game discovery code. For a first pass it might be worth just creating user controllable settings. Even with discovery it may be worth keeping. 

I need to confirm all the "fixes" are in place and then I'll add the options. Ideally these hacks wouldn't be necessary but its not clear to me why they are needed in the first place.
